# Generated by Django 5.2.5 on 2025-08-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_recipe_description_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='comments',
            field=models.ManyToManyField(to='main_app.comment'),
        ),
    ]
