# Generated by Django 5.2.5 on 2025-08-31 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_category_remove_recipe_comments_comment_recipe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='recipe',
            name='categories',
            field=models.CharField(choices=[('S', 'Sweets'), ('A', 'Asian'), ('It', 'Italian')], default='S', max_length=2),
        ),
    ]
