# Generated by Django 5.2.5 on 2025-08-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_category_remove_recipe_categories_recipe_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch')], default='B', max_length=1),
        ),
    ]
